on:
  workflow_call:

permissions:
  contents: write
  packages: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: '1.24.x'
      - uses: open-policy-agent/setup-opa@b2b258e089860efaadaaf71bf6e3aecb4a3eeff1
        with:
          version: 1.6.0
      - name: build bundle
        run: make build
      - name: attach bundle to release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65
        with:
          files: dist/bundle.tar.gz
      - name: install gooci
        run: go install github.com/compliance-framework/gooci@v0.0.7
      - name: gooci login
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gooci login ghcr.io --username "$GH_ACTOR" --password "$GH_TOKEN"
      - name: upload versioned bundle
        env:
          GH_REPOSITORY: ${{ github.repository }}
          GH_REF_NAME: ${{ github.ref_name }}
        run: gooci upload-single dist/bundle.tar.gz "ghcr.io/$GH_REPOSITORY:$GH_REF_NAME"
      - name: upload latest bundle
        if: ${{ startsWith(github.ref, 'refs/tags/') && !contains(github.ref_name, '-') }}
        env:
          GH_REPOSITORY: ${{ github.repository }}
        run: gooci upload-single dist/bundle.tar.gz "ghcr.io/$GH_REPOSITORY:latest"
